### ISSUE TITLE
Compilation Error - Character Creation

### ISSUE THREAD

**Issue by fleekx** [trav346/Questie-Epoch#92]
12:19 Questie: [ERROR] There was an error when compiling data for Quest 26768 "objectives":
12:19 Questie: [ERROR] Interface\AddOns\Questie\Modules\QuestieStream.lua:388: bad argument #1 to 'rshift' (number expected, got table)
12:19 Questie: [ERROR] Error during initialization! Interface\AddOns\Questie\Database\compiler.lua:987: Interface\AddOns\Questie\Modules\QuestieStream.lua:388: bad argument #1 to 'rshift' (number expected, got table)

<img width="1920" height="1080" alt="Image" src="https://github.com/user-attachments/assets/54703e7c-a329-44eb-b4cb-42695340fae8" />

**Comment by trav346** [comment]
Fixed in hotfix2. please update!

**Comment by fleekx** [comment]
> Fixed in hotfix2. please update!

Initialized & compiled successfully. New starter zone quests still not showing up sadly.

<img width="1920" height="1080" alt="Image" src="https://github.com/user-attachments/assets/bf279192-c9e0-44b0-97ce-3f690d21c82d" />

**Comment by trav346** [comment]
Yeah i just confirmed that myself. What the heck, thats no good. Digging in right now.

**Comment by trav346** [comment]
It looks like a person uploaded troll starting quest area but a lot of their quest data was incomplete, signifying that they installed the addon with a log full of quests already. So a lot of the data that will be added is going to be partial. I might just go through the troll starting zone and capture the data myself
